#!/usr/bin/env python
import findrox; findrox.version(2,0,0)
import rox, gtk, os

try:
	__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

	from optparse import OptionParser

	parser = OptionParser()
	parser.add_option("--options",
		action="store_true", dest="options", default=False,
		help="display options dialog without running application")

	(options, args) = parser.parse_args()

	import ripper
	if options.options:
		rox.edit_options()
	else:
		theapp = ripper.Ripper()
		theapp.show()

	rox.mainloop()
except:
	rox.report_exception()
