#!/usr/bin/env python
import findrox; findrox.version(1, 9, 8)
import rox, gtk

import ripper

try:
	gtk.threads_init()
except:
	rox.croak("Ripper needs threads support and you don't have it")

try:
	theapp = ripper.Ripper()
	theapp.show()

	rox.mainloop()
except:
	rox.report_exception()
